import type { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Kanit } from "next/font/google";
import "../globals.css";

const kanit = Kanit({
  variable: "--font-kanit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string }
}) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body className={`${kanit.variable} antialiased font-kanit`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
